# Generated by Django 5.2.9 on 2025-12-24 22:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=256)),
                ("subtitle", models.CharField(max_length=256)),
                ("author", models.CharField(max_length=128)),
            ],
            options={
                "ordering": ["title"],
            },
        ),
    ]
